#!/usr/bin/env python3
"""
Python Compilation Demo 🐍
This script demonstrates how Python compiles source code to bytecode.
"""

import os
import py_compile
import dis
import time
from pathlib import Path

def clear_screen():
    """Clear the terminal screen"""
    os.system('cls' if os.name == 'nt' else 'clear')

def print_header(title):
    """Print a formatted header"""
    print("=" * 60)
    print(f" {title}")
    print("=" * 60)

def demo_compilation_process():
    """Demonstrate Python's compilation process"""
    
    clear_screen()
    print_header("Python Compilation Process Demo")
    
    # Create a sample Python file
    sample_code = '''
# sample_module.py - A simple Python module
def greet(name):
    """Say hello to someone"""
    return f"Hello, {name}! Welcome to Python compilation demo."

def calculate(x, y):
    """Simple calculation"""
    return x * y + 10

# Some sample data
numbers = [1, 2, 3, 4, 5]
message = "This is a sample module"

if __name__ == "__main__":
    print(greet("World"))
    print(f"Calculation: {calculate(5, 3)}")
'''
    
    # Write the sample file
    sample_file = "sample_module.py"
    with open(sample_file, 'w') as f:
        f.write(sample_code)
    
    print(f"✅ Created sample file: {sample_file}")
    print("\n📝 Sample code:")
    print("-" * 40)
    print(sample_code.strip())
    print("-" * 40)
    
    input("\nPress Enter to continue...")
    
    # Step 1: Show compilation
    print_header("Step 1: Manual Compilation")
    print("🔧 Manually compiling Python source to bytecode...")
    
    # Remove any existing .pyc file
    cache_dir = "__pycache__"
    if os.path.exists(cache_dir):
        import shutil
        shutil.rmtree(cache_dir)
        print(f"🗑️ Removed existing {cache_dir} directory")
    
    # Compile the file
    py_compile.compile(sample_file)
    print(f"✅ Compiled {sample_file} to bytecode")
    
    # Show the generated .pyc file
    pyc_files = list(Path(cache_dir).glob("*.pyc")) if os.path.exists(cache_dir) else []
    if pyc_files:
        pyc_file = pyc_files[0]
        print(f"📁 Generated bytecode file: {pyc_file}")
        print(f"📏 Bytecode file size: {pyc_file.stat().st_size} bytes")
    
    input("\nPress Enter to continue...")
    
    # Step 2: Show bytecode disassembly
    print_header("Step 2: Bytecode Disassembly")
    print("🔍 Let's look at the compiled bytecode...\n")
    
    # Import and disassemble the module
    import sample_module
    
    print("🎯 Bytecode for greet() function:")
    print("-" * 40)
    dis.dis(sample_module.greet)
    
    print("\n🎯 Bytecode for calculate() function:")
    print("-" * 40)
    dis.dis(sample_module.calculate)
    
    input("\nPress Enter to continue...")
    
    # Step 3: Performance comparison
    print_header("Step 3: Performance Comparison")
    print("⏱️ Comparing first run vs subsequent runs...\n")
    
    # Remove cache again to simulate first run
    if os.path.exists(cache_dir):
        import shutil
        shutil.rmtree(cache_dir)
    
    # First run (with compilation)
    start_time = time.time()
    import importlib
    spec = importlib.util.spec_from_file_location("sample_module_fresh", sample_file)
    module1 = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module1)
    first_run_time = time.time() - start_time
    
    # Second run (bytecode cached)
    start_time = time.time()
    spec2 = importlib.util.spec_from_file_location("sample_module_cached", sample_file)
    module2 = importlib.util.module_from_spec(spec2)
    spec2.loader.exec_module(module2)
    second_run_time = time.time() - start_time
    
    print(f"🥇 First run (with compilation): {first_run_time:.6f} seconds")
    print(f"🥈 Second run (cached bytecode): {second_run_time:.6f} seconds")
    
    if first_run_time > second_run_time:
        speedup = first_run_time / second_run_time
        print(f"🚀 Speedup: {speedup:.2f}x faster with cached bytecode!")
    
    input("\nPress Enter to continue...")
    
    # Step 4: Show cache directory structure
    print_header("Step 4: Cache Directory Structure")
    print("📁 Exploring the __pycache__ directory...\n")
    
    if os.path.exists(cache_dir):
        print(f"📂 Contents of {cache_dir}:")
        for item in os.listdir(cache_dir):
            full_path = os.path.join(cache_dir, item)
            size = os.path.getsize(full_path)
            print(f"   📄 {item} ({size} bytes)")
            
            # Explain the filename
            if item.endswith('.pyc'):
                parts = item.split('.')
                print(f"      └─ Source: {parts[0]}.py")
                print(f"      └─ Python version: {parts[1]}")
                print(f"      └─ Format: {parts[2]}")
    
    input("\nPress Enter to continue...")
    
    # Step 5: Show what happens in your FastAPI project
    print_header("Step 5: Your FastAPI Project")
    print("🔍 How this applies to your email campaign backend...\n")
    
    print("When you run: python start.py")
    print("└─ 1. 🔧 Compiles start.py → __pycache__/start.cpython-39.pyc")
    print("└─ 2. 🔧 Compiles app/main.py → app/__pycache__/main.cpython-39.pyc")
    print("└─ 3. 🔧 Compiles all imported modules:")
    
    # Show some actual modules from the project
    modules = [
        "app/controllers/natural_language_sql_controller.py",
        "app/services/natural_sql_rag/orchestrator.py",
        "app/services/natural_sql_rag/rag_service.py",
        "app/config/settings.py"
    ]
    
    for module in modules:
        cache_path = module.replace('.py', '.cpython-39.pyc').replace('/', '/__pycache__/')
        cache_path = cache_path.replace('/__pycache__/', '/__pycache__/')
        print(f"   └─ 🔧 {module} → {cache_path}")
    
    print("\n💡 This is why:")
    print("   ✅ First startup takes a bit longer (compilation)")
    print("   ⚡ Subsequent startups are faster (cached bytecode)")
    print("   📁 You see __pycache__ folders everywhere")
    print("   🗑️ It's safe to delete __pycache__ folders")
    
    print("\n🧹 Cleanup...")
    
    # Cleanup
    try:
        os.remove(sample_file)
        if os.path.exists(cache_dir):
            import shutil
            shutil.rmtree(cache_dir)
        print("✅ Cleaned up demo files")
    except Exception as e:
        print(f"⚠️ Cleanup warning: {e}")
    
    print_header("Demo Complete!")
    print("🎉 You now understand Python's compilation process!")
    print("\n💡 Key Takeaways:")
    print("   • Python compiles source code to bytecode automatically")
    print("   • Bytecode is stored in __pycache__ folders")
    print("   • This makes subsequent runs faster")
    print("   • You can safely delete __pycache__ folders")
    print("   • This happens behind the scenes in your FastAPI project")

def show_bytecode_examples():
    """Show some bytecode examples"""
    print_header("Bonus: Bytecode Examples")
    
    print("🔍 Let's see bytecode for some simple operations:\n")
    
    # Simple assignment
    def simple_assignment():
        x = 42
        return x
    
    print("📝 Code: x = 42; return x")
    print("🤖 Bytecode:")
    dis.dis(simple_assignment)
    
    print("\n" + "-" * 50 + "\n")
    
    # Loop example
    def simple_loop():
        total = 0
        for i in range(3):
            total += i
        return total
    
    print("📝 Code: for i in range(3): total += i")
    print("🤖 Bytecode:")
    dis.dis(simple_loop)

if __name__ == "__main__":
    try:
        demo_compilation_process()
        
        print("\n" + "=" * 60)
        choice = input("\nWant to see bytecode examples? (y/n): ").lower().strip()
        if choice in ['y', 'yes']:
            show_bytecode_examples()
            
    except KeyboardInterrupt:
        print("\n\n👋 Demo interrupted. Thanks for exploring Python compilation!")
    except Exception as e:
        print(f"\n❌ Error during demo: {e}")
        print("💡 This is just a demonstration - your actual project is unaffected!")
